config/routes.rb
Company::Application.routes.draw do
  resources :divisions
  root :to => 'divisions#index'
  match "/division/:id/edit", :controller => "division", :action => "edit"

end

app/models/division.rb
class Division < ActiveRecord::Base
	validates :name, :presence => { :message => " of Branch can not be left blank" }, :length => { :in => 2..40, :message => " of Branch must be between 2 to 40 charachters long" }
	
	validates :phonenumber, :presence => { :message => " can not be left blank" },:numericality => { :only_integer => true, :message => " can only consist of digits" }, :length => { :is => 10, :message => " must be 10 digits long" }

	validates :address, :presence => { :message => " of Branch can not be left blank" }

	validates :alternatephonenumber, :numericality => { :only_integer => true, :message => " can only consist of digits" }, :length => { :is => 10, :message => " must be 10 digits long" }, :allow_blank => true

	validates :operationstartedon, :presence => { :message => " please select a date" } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= simple_form_for(@division) do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


		<form id="f1 box">
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Name, :class =>"label_name" %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :name, :class => "style2", :placeholder => 'Name of branch' %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Phone_Number, :class =>"label_name", :label => "Phone Number" %>
					<span class="style2">
    						<%= f.text_field :phonenumber, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
    							<%= f.label :Alternate_Phone, :class =>"label_name", :label => "Alternamte Phone"   %>
							<span class="style2">
    								<%= f.text_field :alternatephonenumber, :class => "style2" %>
							</span>
						</div>
						<div id="innerblock_left_sub" >
					<%= f.input :pricingcategory, :label_html => { :class => 'label_name' }, :label => "Pricing Category" , :collection => [["Head Office Management"], ["Branch Office Management"]], :include_blank => false %> 
						</div>
					</div>
					<div id="innerblock_right">
						<%= f.label :Description, :class =>"label_name"  %>
						<span class="style2">
    							<%= f.text_area :description, :rows => 8, :cols => 30, :class => "style1"  %>
						</span>
					</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.label :Online_Branch, :class =>"label_name", :label => "Online Branch"   %>
					<span class="style2" >
    						<%= f.check_box :onlinebranch, :class => "style5" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Operation_Started_On, :class =>"label_name" , :label => "Operation Started On"  %>
					<span class="style2">
    						<%= f.date_select :operationstartedon, :class => "style2" %>
					</span>
				</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.label :Address, :class =>"label_name"  %>
					<span class="style2">
    						<%= f.text_area :address, :rows => 8, :cols => 30, :class => "style1" %>
					</span>
				</div>
					
				<div id="innerblock_right">
    					<%= f.label :Comments, :class =>"label_name"  %>
					<span class="style2">
    						<%= f.text_area :comments, :rows => 8, :cols => 30, :class => "style1"  %>
					</span>
				</div>
				</div>

				<div class="block">
				<div id="innerblock_left">
					<%= f.label :active, :class =>"label_name"   %>
					<span class="style2" >
    						<%= f.check_box :active, :class => "style5" %>
					</span>
				</div>
			<div class="block  block_bt">
				<span>
					<input class="style3" type="submit" value="Add Branch" name="n10"  >
				</span>
				<span>
					<input class="style3" type="submit" value="Cancel" name="n10" >
				</span>
			</div>
		</form>

<% end %>

app/views/divisions/edit.html.erb
<div class="header_bg">
	<h2> Edit Branch Details </h2>
</div>
<%= render 'form' %>

<!--
<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>
-->

app/views/divisions/index.html.erb
	

	<div class="header_bg">
			<h2> Branch List </h2>
			
		</div>
		<div class="branch_button">
		
		<img src="../images/search.png" width="153" height="35" border="none"/>
	   <a href="divisions/new.html">
		<img src="../images/addbutton.png" width="128" height="40" border="none"/></a>
		
	   <a href='#'>	
		<img src="../images/editbutton.png" width="128" height="39" border="none" onClick='alert("Please select a branch to edit")'/>
		</a></div>
		<div class="branch_text"> <a href="default.asp">Advanced Search</a></div>


<table class="index_box">
  <tr>
    <th class="maintitle user_radio bg_listholder"></th>
    <th class="maintitle bg_listholder">ID</th>
    <th class="maintitle bg_listholder">Name</th>
    <th class="maintitle bg_listholder">Address</th>
    <th class="maintitle bg_listholder">Phone Number</th>
    <th class="maintitle bg_listholder">Status</th>
  </tr>


<% @divisions.each do |division| %>
  <tr class="<%= cycle('title', 'bg_grey') %> ">
    <td class="user_radio"><%= radio_button_tag("division_ids[]", division.id, false, :onClick => 'location.href="' + edit_division_path(division) + '"'
)%></td>
    <td class="branch_id" id="bg_listholder"><%= division.id %></td>
    <td class="branch_name" id="bg_listholder"><%= division.name %></td>
    <td class="branch_address" id="bg_listholder"><%= division.address %></td>
    <td class="branch_number" id="bg_listholder"><%= division.phonenumber %></td>
    <% if division.active == false %>
				<td class="user_status" id="bg_listholder"><img src="../images/tick.png" width="31" height="34"/></li>
			<% elsif %>
				<td class="user_status" id="bg_listholder"><img src="../images/untick.png" width="31" height="34"/></li>
   <% end %>
  </tr>

<% end %>
</table>

app/views/divisions/new.html.erb
<div class="header_bg">
	<h2> Add a new branch </h2>
</div>
<%= render 'form' %>

<!--
<%= link_to 'Back', divisions_path %>
-->

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @division.name %>
</p>

<p>
  <b>Description:</b>
  <%= @division.description %>
</p>

<p>
  <b>Address:</b>
  <%= @division.address %>
</p>

<p>
  <b>Phonenumber:</b>
  <%= @division.phonenumber %>
</p>

<p>
  <b>Alternatephonenumber:</b>
  <%= @division.alternatephonenumber %>
</p>

<p>
  <b>Pricingcategory:</b>
  <%= @division.pricingcategory %>
</p>

<p>
  <b>Onlinebranch:</b>
  <%= @division.onlinebranch %>
</p>

<p>
  <b>Active:</b>
  <%= @division.active %>
</p>

<p>
  <b>Operationstartedon:</b>
  <%= @division.operationstartedon %>
</p>

<p>
  <b>Comments:</b>
  <%= @division.comments %>
</p>


<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd"> 

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <title>Branch List</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

	<div class="header">
	
		<div class="logo">
			<a href="head_control_panel.html"><img src="/images/logo.png"  width="305" height="126" border="none"/></a>   
		</div>
		<div class="menu_holder">
			
			<div class="logged_user"> Welcome Admin <span><a href="default.asp"><img src="/images/logout.png" width="24" height="23" border="none"/><b> Logout</b></a>  
			</span>
			</div>
			<div class="date">
			<%= Time.now %>				
			</div>
			<ul class="menu">
			
			<b>
			<li><a href="usermanagement.html">System</a></li>
			<li><a href="branch_list.html">Branches</a></li>
			<li><a href="employee_management.html">Employees</a></li>
			<li><a href="treatment_management.html">Treatments</a></li>
			<li><a href="product_management.html">Stock</a></li>
			<li><a href="#">Reports</a></li>
			</b>
			
			</ul>
		</div>
		
	</div>
	<div class="box">
	<%= yield %>
	</div> 
</div>
<div class="footer">
	Copyright &copy; 2012 <b>CDMS</b>. All rights reserved.
</div>	
	

</body>
</html>